# S3c24XX Platform Support
snd-soc-s3c24xx-i2s-objs := s3c24xx-i2s.o
snd-soc-s3c-objs := s3c-pcm.o
snd-soc-s3c-i2s-objs := s3c-i2s.o
snd-soc-s3c2443-ac97-objs := s3c2443-ac97.o
snd-soc-s3c2450-ac97-objs := s3c2450-ac97.o
snd-soc-s3c2450-i2s-objs  := s3c2450-i2s.o

obj-$(CONFIG_SND_S3C_SOC) += snd-soc-s3c.o
obj-$(CONFIG_SND_S3C_SOC_I2S) += snd-soc-s3c-i2s.o
obj-$(CONFIG_SND_S3C2443_SOC_AC97) += snd-soc-s3c2443-ac97.o
obj-$(CONFIG_SND_S3C2450_SOC_AC97) += snd-soc-s3c2450-ac97.o
obj-$(CONFIG_SND_S3C2450_SOC_I2S) += snd-soc-s3c2450-i2s.o

# S3C24XX Machine Support
snd-soc-neo1973-wm8753-objs := neo1973_wm8753.o
snd-soc-smdk2443-wm9710-objs := smdk2443_wm9710.o
snd-soc-smdk2450-wm9713-objs := smdk2450_wm9713.o
snd-soc-smdk2450-wm8580-objs := smdk2450_wm8580.o

obj-$(CONFIG_SND_S3C24XX_SOC_NEO1973_WM8753) += snd-soc-neo1973-wm8753.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2443_WM9710) += snd-soc-smdk2443-wm9710.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2450_WM9713) += snd-soc-smdk2450-wm9713.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2450_WM8580) += snd-soc-smdk2450-wm8580.o
